core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('', include('admin_material.urls'))
]

home/models.py
from django.db import models
from django.contrib import admin
from core import settings


class Chef_de_Projet(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    Chef_de_Projet_name = models.CharField(max_length=200, null=True)
    Chef_de_Projet_Prenom = models.CharField(max_length=200)
    Chef_de_Projet_mail = models.CharField(max_length=200)
    Chef_de_Projet_mot_de_passe = models.CharField(max_length=200)

    idChef_de_Projet = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Chef_de_Projet_name


class Responsable_Projet(admin.ModelAdmin):
    list_display = ('Chef_de_Projet_name', 'Chef_de_Projet_Prenom',)
    search_fields = ['Chef_de_Projet_name', 'Chef_de_Projet_Prenom', ]


class Equipe_de_Projet(models.Model):
    Nom_Employe = models.CharField(max_length=200, null=True)
    Services = models.CharField(max_length=200)

    idProjet = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Nom_Employe


class Teams_Projet(admin.ModelAdmin):
    list_display = ('Nom_Employe', 'Services',)
    search_fields = ['Nom_Employe', 'Services', ]


##


class Categorie(models.Model):
    Domaine_dactivite = models.CharField(max_length=200, null=True)

    iddomaine_dactivite = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Domaine_dactivite


class genre(admin.ModelAdmin):
    list_display = ('Domaine_dactivite',)
    search_fields = ['Domaine_dactivite', ]


##


class Livrable(models.Model):
    nom_livrable = models.CharField(max_length=200, null=True)
    Ref_livrable = models.CharField(max_length=200, null=True)
    Type = models.CharField(max_length=200, null=True)

    idlivrable = models.AutoField(primary_key=True)

    def __str__(self):
        return self.nom_livrable


class document(admin.ModelAdmin):
    list_display = ('nom_livrable', 'Ref_livrable', 'Type')
    search_fields = ['Type', ]


##


class Cycle_de_devellopement(models.Model):
    type = models.CharField(max_length=200, null=True)
    Date_debut = models.CharField(max_length=200)
    Date_Fin = models.CharField(max_length=200)
    Priorite = models.CharField(max_length=200)

    # clé étrangère d'une autre table #
    nom_livrable = models.ForeignKey(Livrable, on_delete=models.CASCADE, null=True)
    ##
    idphase = models.AutoField(primary_key=True)

    def __str__(self):
        return self.type


class Cycle_de_vie(admin.ModelAdmin):
    list_display = ('type', 'Priorite',)
    search_fields = ['type', 'Priorite', ]


##

class Etape(models.Model):
    # clé étrangère d'une autre table #
    type = models.ForeignKey(Cycle_de_devellopement, on_delete=models.CASCADE, null=True)
    #
    num_etape = models.CharField(max_length=200, null=True)
    nom_etape = models.CharField(max_length=200, null=True)
    Statut = models.CharField(max_length=200, null=True)
    Commentaire = models.CharField(max_length=200, null=True)

    idEtape = models.AutoField(primary_key=True)

    def __str__(self):
        return self.nom_etape


class sequence(admin.ModelAdmin):
    list_display = ('type', 'num_etape', 'nom_etape', 'Statut', 'Commentaire',)
    search_fields = ['Statut', ]


##


class Client(models.Model):
    Nom_Client = models.CharField(max_length=200, null=True)
    Adresse = models.CharField(max_length=200)
    # clé étrangère d'une autre table #
    Domaine_dactivite = models.ForeignKey(Categorie, on_delete=models.CASCADE, null=True)
    ##
    idClient = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Nom_Client


class customer(admin.ModelAdmin):
    list_display = ('Nom_Client', 'Adresse', 'Domaine_dactivite')
    search_fields = ['Nom_Client', 'Adresse', 'Domaine_dactivite']
    list_filter = ['Domaine_dactivite']


class Famille_de_Projet(models.Model):
    Nom_Famille = models.CharField(max_length=200, null=True)

    idFamille = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Nom_Famille


class Family(admin.ModelAdmin):
    list_display = ('Nom_Famille',)
    search_fields = ['Nom_Famille', ]


# CLASS DE "TYPE DE PROCESS" ASSOCIE A UN PROJET
class Process(models.Model):
    nom = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nom


class ProcessAdmin(admin.ModelAdmin):
    list_display = ('nom',)


class Projet(models.Model):
    nom = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=200)
    nom_client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    chef_de_projet = models.ForeignKey(Chef_de_Projet, on_delete=models.CASCADE, null=True)
    Date_debut = models.DateTimeField(null=True)
    Date_fin = models.DateTimeField(null=True)
    type_process = models.ForeignKey(Process, on_delete=models.CASCADE, null=True)
    id_projet = models.AutoField(primary_key=True)

    def __str__(self):
        return self.nom

    def progress(self):
        all_tasks = Tache.objects.filter(projet=self)
        total_progress = sum(task.progression_tache() for task in all_tasks)
        total_tasks_count = all_tasks.count()

        if total_tasks_count == 0:
            return 0.0

        return total_progress / total_tasks_count


# CLASS DE "MODEL" DU "TYPE DE PROCESS" ASSOCIE A UN PROJET
class ModelProcess(models.Model):
    nom = models.CharField(max_length=150)
    process = models.ForeignKey(Process, on_delete=models.CASCADE, related_name='models')
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nom

    def progression_taches(self):
        """ Calcul la progression des tâches dans un model spécifique d'un type de process """
        total_model_taches = self.tache_set.all().count()
        total_model_taches_achevees = self.tache_set.filter(acheve=True).count()
        if total_model_taches == 0:
            return 0.0
        return (total_model_taches_achevees / total_model_taches) * 100


class ModelProcessAdmin(admin.ModelAdmin):
    list_display = ('nom', 'process',)
    search_fields = ['nom', 'process']
    list_filter = ['nom']


# CLASS DE TACHES D'UN MODEL SPECIFIQUE D'UN PROCESS ASSOCIE A UN PROJET DONNE
class Tache(models.Model):
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE, null=True)
    model = models.ForeignKey(ModelProcess, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    date_achevement = models.DateTimeField(null=True, blank=True)
    acheve = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.description} - {'Achevée' if self.acheve else 'Non achevée'}"

    def progression_tache(self):
        return 100 if self.acheve else 0


class Commentaire(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    model = models.ForeignKey(ModelProcess, on_delete=models.CASCADE)
    contenu = models.TextField()
    response = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)


class CommentaireAdmin(admin.ModelAdmin):
    list_display = ('creator', 'model',)


class TacheAdmin(admin.ModelAdmin):
    list_display = ('model', 'description', 'acheve')


class programme(admin.ModelAdmin):
    list_display = ('nom', 'type_process', 'description', 'nom_client', 'chef_de_projet',)
    search_fields = ['nom', 'etat', 'description']
    list_filter = ['nom']


##


class Site(models.Model):
    Nom_Site = models.CharField(max_length=200, null=True)
    idsite = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Nom_Site


class emplacement(admin.ModelAdmin):
    list_display = ('Nom_Site',)
    search_fields = ['Nom_Site', ]


##

class Avancement(models.Model):
    etat_avancement = models.CharField(max_length=200, null=True)

    idavancement = models.AutoField(primary_key=True)

    def __str__(self):
        return self.etat_avancement


class Progression(admin.ModelAdmin):
    list_display = ('etat_avancement',)
    search_fields = ['etat_avancement', ]


##

class Equipements(models.Model):
    Nom_Equipement = models.CharField(max_length=200, null=True)
    type_Equipement = models.CharField(max_length=200)
    statut_Equipement = models.CharField(max_length=200)
    Numero_Equipement = models.CharField(max_length=200, null=True)

    idequipement = models.AutoField(primary_key=True)

    def __str__(self):
        return self.Nom_Equipement


class outillage(admin.ModelAdmin):
    list_display = ('Numero_Equipement', 'type_Equipement')
    search_fields = ['statut_Equipement', ]

templates/pages/add_category.html
{% extends 'layouts/base.html' %}

{% block title %} Créer une catégorie {% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <h3 class="text-center">Créer un domaine d'activité</h3>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success mt-3">Créer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/add_tache.html
{% extends 'layouts/base.html' %}

{% block title %} Créer une nouvelle tâche {% endblock title %}

{% block content %}
<div class="container mt-5">
    <a href="{% url 'detail-model' model.id %}" class="btn btn-secondary">Go back</a>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Créer une nouvelle tâche</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Créer</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/add_task.html
{% extends 'layouts/base.html' %}

{% load static i18n %}

{% block title %} Map {% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">Ajouter une tâche</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Ajouter</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/affiche.html
{% extends 'layouts/base.html' %}

{% load static i18n %}

{% block title %} Map {% endblock title %}

{% block content %}
<div class="col-md-12">
     {% if messages %}
        {% for message in messages %}
        <div class="alert alert-secondary text-white" role="alert">
           {{ message }}
        </div>
        {% endfor%}
        {% endif %}
    <div class="card">
        <div class="card-header">
            <strong>{{ projects.count }} Projets Actifs</strong>
        </div>
        <div class="card-body">
            <div class="row">
                {% for project in projects %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card mx-2">
                        <div class="card-body">
                            <div class="h4 m-0 lead text-info">
                                {{ project.nom }}
                            </div>
                            <p class="text-muted mb-0 text-right">{{ project.calculer_progres }}%</p>
                            <span class="mt-2">Progress</span>
                            <div class="progress progress-xs mb-3">
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{ project.calculer_progres }}%" aria-valuenow="{{ project.calculer_progres }}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                            <small class="text-muted">{{ project.description }}</small>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Client: {{ project.nom_client }}</small>
                            <a href="{% url 'detail-projet' project.id_projet %}" class="btn btn-sm btn-primary float-end">Voir Détails</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
</div>

{% endblock %}

templates/pages/creer_model.html
{% extends 'layouts/base.html' %}

{% block title %}Créer un modèle de processus{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h2>Créer un nouveau modèle de processus</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Créer</button>
    </form>
</div>
{% endblock content %}

templates/pages/detail_model_process.html
{% extends 'layouts/base.html' %}

{% load static i18n %}


{% block title %} Ajouter un projet {% endblock title %}


{% block content %}
<div class="container mt-5">
    {% if messages %}
    {% for message in messages %}
    <div id="alertMessage" class="alert alert-secondary alert-dismissible fade show text-white" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                style="background-color: rgba(255, 255, 255, 0.5);">
            <span aria-hidden="true"><i class="fas fa-times text-white"></i></span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="row">
        <div>
            <a href="{% url 'detail-projet' project.id_projet %}" class="btn btn-secondary">Go Back</a>
        </div>
        <div class="col">
            <h3>Tâches du modèle {{ model.nom }}</h3>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Description</th>
                    <th scope="col">Date Achèvement</th>
                    <th scope="col">Achevée</th>
                    {% if is_chef_projet or request.user.is_superuser %}
                    <th scope="col">Action</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for tache in model.tache_set.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ tache.description }}</td>
                    <td>{{ tache.date_achevement|date:"d F Y" }}</td>
                    <td>
                        {% if tache.acheve %}
                        <img src="{% static 'img/true.png' %}" alt="True"
                             style="max-width: 15px; height: auto; margin-left:30px;">
                        {% else %}
                        <img src="{% static 'img/false.png' %}" alt="False"
                             style="max-width: 15px; height: auto; margin-left:30px;">
                        {% endif %}
                    </td>
                    {% if is_chef_projet or request.user.is_superuser %}
                    <td>
                        <a href="{% url 'modify-task' model.id tache.id %}" class="btn btn-secondary">Modifier</a>
                    </td>
                    <td>
                        <a href="{% url 'delete-task' model.id tache.id %}" class="btn btn-danger">Supprimer</a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_chef_projet or request.user.is_superuser %}
            <a href="{% url 'create-task' model.id %}" class="btn btn-success">Créer une nouvelle tâche</a>
            {% endif %}

            <!-- Affichage des commentaires de l'utilisateur -->
            <div class="card mt-5">
                {% if commentaires %}
                <div class="card-header">
                    Vos commentaires
                </div>
                {% endif %}
                <div class="card-body">
                    {% for commentaire in commentaires %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <p class="card-text">{{ commentaire.contenu }}</p>
                            <p class="card-text text-muted">@{{ commentaire.creator }}</p>
                        </div>
                    </div>
                    {% empty %}
                    {% if not is_chef_projet or request.user.is_superuser %}
                    <p class="card-text">Vos commentaires apparaîtront ici une fois ajoutés.</p>
                    {% else %}
                    <p class="card-text">Vous n'avez aucun commentaire pour le moment</p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% if not is_chef_projet or request.user.is_superuser %}
            <!-- Formulaire pour laisser un commentaire -->
            <div class="card mt-3">
                <div class="card-header">
                    Laisser un commentaire
                </div>
                <div class="card-body">
                    <form action="{% url 'ajouter_commentaire' model.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="model_id" value="{{ model.id }}">
                        <div class="mb-3">
                            <label for="commentaire" class="form-label">Votre commentaire :</label>
                            <textarea class="form-control border px-2" name="contenu" id="commentaire" rows="5"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">Publier</button>
                    </form>
                </div>
            </div>
            {% else %}
            {% if commentaires %}
             <div class="card mt-3">
                <div class="card-header">
                    Repondre
                </div>
                <div class="card-body">
                    <form action="{% url 'ajouter_commentaire' model.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="model_id" value="{{ model.id }}">
                        <div class="mb-3">
                            <label for="commentaire" class="form-label">Votre commentaire :</label>
                            <textarea class="form-control border px-2" name="contenu" id="comment" rows="5"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">Publier</button>
                    </form>
                </div>
            </div>
            {% endif %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock content %}

templates/pages/detail_project.html
{% extends 'layouts/base.html' %}
{% load static i18n %}


{% block title %} Détail du projet {% endblock title %}

{% block content %}


<div class="container mt-5">
    {% if messages %}
    {% for message in messages %}
    <div id="alertMessage" class="alert alert-secondary alert-dismissible fade show text-white" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"
                style="background-color: rgba(255, 255, 255, 0.5);">
            <span aria-hidden="true"><i class="fas fa-times text-white"></i></span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="mb-4">
        <a href="{% url 'display' %}" class="btn btn-secondary">Go back</a>
    </div>
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card border border-dark">
                    <div class="card-body">
                        <h5 class="card-title mb-4">Informations du projet</h5>
                        <div class="mb-3">
                            <p><strong>Nom:</strong> {{ projet.nom }}</p>
                            <p><strong>Chef de projet:</strong> {{ projet.chef_de_projet }}</p>
                            <p><strong>Description:</strong> {{ projet.description }}</p>
                            <div class="input-group mb-3">
                                <span class="input-group-text">Path du Projet:</span>
                                <textarea class="form-control border border-dark" rows="1"
                                          readonly>{{ projet.path }}</textarea>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md">
                                <label for="nrc_estime" class="form-label">Chiffrage NRC Estimé:</label>
                                <textarea id="nrc_estime" class="form-control border border-dark" rows="1"
                                          cols="10"></textarea>
                            </div>
                            <div class="col-md">
                                <label for="nrc_consomme" class="form-label">Chiffrage NRC Consommé:</label>
                                <textarea id="nrc_consomme" class="form-control border border-dark" rows="1"
                                          cols="10"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md">
                                <label for="nre_estime" class="form-label">Chiffrage NRE Estimé:</label>
                                <textarea id="nre_estime" class="form-control border border-dark" rows="1"
                                          cols="10"></textarea>
                            </div>
                            <div class="col-md">
                                <label for="nre_consomme" class="form-label">Chiffrage NRE Consommé:</label>
                                <textarea id="nre_consomme" class="form-control border border-dark" rows="1"
                                          cols="10"></textarea>
                            </div>
                        </div>
                    </div>
                    <!-- Options de modification et de suppression -->

                    <div class="card-footer d-flex justify-content-end">
                        {% if request.user.is_superuser%}
                        <a href="{% url 'update-projet' projet.id_projet %}" class="btn btn-success me-2">Modifier le
                            projet</a>
                        <a href="{% url 'delete-projet' projet.id_projet %}" class="btn btn-danger">Supprimer le
                            projet</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <h4 class="text-center">Models du type de processus</h4>
        {% for modele_process in modeles %}
        <div class="col-lg-3 mb-3">
            <a href="{% url 'detail-model' modele_process.id %}" class="text-decoration-none">
                <div class="card border border-dark m-2 overflow-hidden">
                    <div class="card-header m-0 p-2">{{ modele_process.nom }}</div>
                </div>
            </a>
            <div class="card border border-dark m-2 overflow-hidden">
                <span class="text-dark mb-1 p-2">Avancement</span>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="progress" style="flex-grow: 1;">
                            <div class="progress-bar bg-success" role="progressbar"
                                 style="width: {{ modele_process.progression_taches }}%;"
                                 aria-valuenow="{{ modele_process.progression_taches }}" aria-valuemin="0"
                                 aria-valuemax="100">
                            </div>
                        </div>
                        <span>{{ modele_process.progression_taches|floatformat:2 }}%</span>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/pages/icons.html
{% extends 'layouts/base.html' %}
{% load static i18n %}

{% block title %} Icons {% endblock title %}  

{% block content %}

    <div class="container-fluid py-4">
      <div class="row min-vh-80">
        <div class="col-6 mx-auto">
          <div class="card mt-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Material Design Icons</h6>
                <p class="mb-0 text-white ps-3">Handcrafted by our friends from
                  <a class="text-white font-weight-bold" target="_blank" href="https://fonts.google.com/icons">Google</a>
                </p>
              </div>
            </div>
            <div class="card-body">
              <p>Through most of the examples in this dashboard, we have used the default <a href="https://fonts.google.com/icons">Icons for the Material Design</a> provided by Google.</p>
              <i class="material-icons text-2xl">face</i>
            </div>
          </div>
        </div>
      </div>
      {% include 'includes/footer.html' %}
    </div>
    {% endblock content %}
 

templates/pages/update_projet.html
{% extends 'layouts/base.html' %} {% load static i18n %} {% block title %}
Ajouter un projet {% endblock title %} {% block content %}
<div class="container mt-5">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-secondary text-white" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <h3 class="text-center">
          Modifier le projet :
          <span class="fs-20 fw-400 text-success">
            <small> {{ projet.nom }}</small>
          </span>
        </h3>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_nom">Nom du projet</label>
              {{ form.nom }}
            </div>
            <div class="form-group">
              <label for="id_type_process">Type de processus</label>
              <div class="row align-items-center">
                <div class="col">{{ form.type_process }}</div>
                <div class="col-auto">
                  <a href="{% url 'type-process' %}" class="btn btn-success"
                    ><i class="fas fa-plus-circle"></i> Ajouter</a
                  >
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="id_nom_client">Nom du client</label>
              <div class="row align-items-center">
                <div class="col">{{ form.nom_client }}</div>
                <div class="col-auto">
                  <a href="{% url 'add-client' %}" class="btn btn-success"
                    ><i class="fas fa-plus-circle"></i> Ajouter</a
                  >
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="id_chef_de_projet">Chef de projet</label>
              <div class="row align-items-center">
                <div class="col">{{ form.chef_de_projet }}</div>
                <div class="col-auto">
                  <a href="{% url 'add-chef-projet' %}" class="btn btn-success"
                    ><i class="fas fa-plus-circle"></i> Ajouter</a
                  >
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="id_Date_debut">Date de début</label>
              <input
                type="text"
                class="form-control"
                style="border: 1px solid #ced4da"
                id="datepicker-debut"
                name="Date_debut"
              />
              {% for error in form.Date_debut.errors %}
              <div class="invalid-feedback">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="form-group">
              <label for="id_Date_fin">Date de fin</label>
              <input
                type="text"
                class="form-control"
                style="border: 1px solid #ced4da"
                id="datepicker-fin"
                name="Date_fin"
              />
              {% for error in form.Date_fin.errors %}
              <div class="invalid-feedback">{{ error }}</div>
              {% endfor %}
            </div>
            <div class="form-group">
              <label for="id_description">Description</label>
              {{ form.description }}
            </div>
            <button type="submit" class="btn btn-success mt-3">Modifier</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}